{% set name = "fibermorph" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fibermorph-{{ version }}.tar.gz
  sha256: REPLACE_WITH_SHA256_FROM_PYPI  # Get from https://pypi.org/project/fibermorph/0.3.9/#files

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - fibermorph = fibermorph.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core <1.9
  run:
    - python >=3.9,<3.14
    - numpy >=1.26.4
    - joblib >=1.3.2,<2.0.0
    - pandas >=2.2.0,<3.0.0
    - pillow >=10.2.0,<11.0.0
    - requests >=2.31.0,<3.0.0
    - scipy >=1.8,<2.0
    - tqdm >=4.66.1,<5.0.0
    - scikit-image >=0.22.0,<0.23.0

test:
  imports:
    - fibermorph
    - fibermorph.core
    - fibermorph.analysis
    - fibermorph.processing
    - fibermorph.io
    - fibermorph.utils
  commands:
    - fibermorph --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lasisilab/fibermorph
  summary: 'Toolkit for analyzing hair fiber morphology from microscopy images'
  description: |
    fibermorph is a Python package for automated image analysis of hair fiber 
    morphology. It provides tools for analyzing fiber curvature and cross-sectional 
    properties from microscopy images, including automated detection, measurement, 
    and statistical analysis of fiber characteristics.
    
    Key features:
    - Automated fiber detection and segmentation
    - Curvature analysis with configurable window sizes
    - Cross-section analysis
    - Batch processing capabilities
    - Comprehensive statistical outputs
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/lasisilab/fibermorph/blob/main/README.md
  dev_url: https://github.com/lasisilab/fibermorph

extra:
  recipe-maintainers:
    - tlasisi  # Replace with your GitHub username if different
