"""Removed curvature options: a clear error (exit code 2) and no --help entry.

Scripts written for earlier versions (for example SBATCH scripts generated by
the web app) may still pass these flags. They must stop with a message that
says why, rather than silently running a different analysis or failing with
argparse's generic "unrecognized arguments".
"""

import pytest

from fibermorph import cli

# flag -> the feature the error message names
REMOVED_OPTIONS = {
    "--use-clahe": "CLAHE preprocessing",
}


def _parse(monkeypatch, *argv):
    monkeypatch.setattr("sys.argv", ["fibermorph", *argv])
    return cli.parse_args()


@pytest.mark.parametrize("flag", REMOVED_OPTIONS)
def test_removed_option_exits_with_code_2_and_explains_why(monkeypatch, capsys, flag):
    with pytest.raises(SystemExit) as excinfo:
        _parse(monkeypatch, "--curvature", "-i", "in", "-o", "out", flag)
    assert excinfo.value.code == 2

    err = capsys.readouterr().err
    assert f"argument {flag}" in err
    assert "was removed" in err
    assert REMOVED_OPTIONS[flag] in err
    assert "not part of the published fibermorph curvature method" in err
    assert "unrecognized arguments" not in err


@pytest.mark.parametrize("flag", REMOVED_OPTIONS)
def test_removed_option_is_rejected_wherever_it_appears(monkeypatch, capsys, flag):
    with pytest.raises(SystemExit) as excinfo:
        _parse(monkeypatch, flag, "--curvature", "--resolution_mm", "132",
               "-i", "in", "-o", "out")
    assert excinfo.value.code == 2
    assert "was removed" in capsys.readouterr().err


@pytest.mark.parametrize("flag", REMOVED_OPTIONS)
def test_removed_option_is_hidden_from_help(monkeypatch, capsys, flag):
    with pytest.raises(SystemExit) as excinfo:
        _parse(monkeypatch, "--help")
    assert excinfo.value.code == 0

    out = capsys.readouterr().out
    assert "--within_element" in out  # the curvature options are still listed
    assert flag not in out


def test_curvature_command_without_removed_options_still_parses(monkeypatch):
    args = _parse(monkeypatch, "--curvature", "-i", "in", "-o", "out")
    assert args.curvature is True
    for flag in REMOVED_OPTIONS:
        assert not hasattr(args, flag.lstrip("-").replace("-", "_"))
