name: Release

# release on push version tag, e.g. v0.3.2
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.11

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Check if tag matches the package version
        run: |
          PKG_VERSION=$(poetry version -s)
          TAG=${GITHUB_REF#refs/tags/}
          if [[ "v$PKG_VERSION" != "$TAG" ]]; then
            echo "Error: Tag ($TAG) does not match the package version (v$PKG_VERSION)."
            exit 1
          fi

      - name: Install Dependencies using Poetry
        run: poetry build

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "dist/*"

      - name: Publish to PyPi
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD